name: CI/CD Go

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do Codigo
      uses: actions/checkout@v2   

    - name: Configurar o Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: build
      run: go build -v ./...

    - name: Testes
      run: go test -v ./...   
