name: CI/CD Go

on:
  push:
    branches:
      - main


jobs:    
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do Codigo
      uses: actions/checkout@v2   

    - name: Configurar o Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: build instala dependencias e gera executavel
      run: go build -v ./...
  

  test:
    name: Test
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do Codigo
      uses: actions/checkout@v2   

    - name: Configurar o Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Testes
      run: go test -v ./...   
